<?php
declare(strict_types=1);

// SvobodaWeb SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SvobodaWebUtility::setRegistrar(function (SvobodaWebUtility $u): void {
    $u->clean = [SvobodaWebClean::class, 'call'];
    $u->done = [SvobodaWebDone::class, 'call'];
    $u->make_error = [SvobodaWebMakeError::class, 'call'];
    $u->feature_add = [SvobodaWebFeatureAdd::class, 'call'];
    $u->feature_hook = [SvobodaWebFeatureHook::class, 'call'];
    $u->feature_init = [SvobodaWebFeatureInit::class, 'call'];
    $u->fetcher = [SvobodaWebFetcher::class, 'call'];
    $u->make_fetch_def = [SvobodaWebMakeFetchDef::class, 'call'];
    $u->make_context = [SvobodaWebMakeContext::class, 'call'];
    $u->make_options = [SvobodaWebMakeOptions::class, 'call'];
    $u->make_request = [SvobodaWebMakeRequest::class, 'call'];
    $u->make_response = [SvobodaWebMakeResponse::class, 'call'];
    $u->make_result = [SvobodaWebMakeResult::class, 'call'];
    $u->make_point = [SvobodaWebMakePoint::class, 'call'];
    $u->make_spec = [SvobodaWebMakeSpec::class, 'call'];
    $u->make_url = [SvobodaWebMakeUrl::class, 'call'];
    $u->param = [SvobodaWebParam::class, 'call'];
    $u->prepare_auth = [SvobodaWebPrepareAuth::class, 'call'];
    $u->prepare_body = [SvobodaWebPrepareBody::class, 'call'];
    $u->prepare_headers = [SvobodaWebPrepareHeaders::class, 'call'];
    $u->prepare_method = [SvobodaWebPrepareMethod::class, 'call'];
    $u->prepare_params = [SvobodaWebPrepareParams::class, 'call'];
    $u->prepare_path = [SvobodaWebPreparePath::class, 'call'];
    $u->prepare_query = [SvobodaWebPrepareQuery::class, 'call'];
    $u->graphql_body = [SvobodaWebGraphql::class, 'body'];
    $u->graphql_errors = [SvobodaWebGraphql::class, 'errors'];
    $u->result_basic = [SvobodaWebResultBasic::class, 'call'];
    $u->result_body = [SvobodaWebResultBody::class, 'call'];
    $u->result_headers = [SvobodaWebResultHeaders::class, 'call'];
    $u->transform_request = [SvobodaWebTransformRequest::class, 'call'];
    $u->transform_response = [SvobodaWebTransformResponse::class, 'call'];
});
